teams:
- name: dcql-ts-maintainers
  maintainers:
  - TimoGlastra
  members:
  - auer-martin
- name: dcql-ts-admin
  maintainers:
  - TimoGlastra
  members:
  - auer-martin
- name: pydentity-wallet-maintainers
  maintainers:
  - PatStLouis
  members:
  - jamshale
  - esune
  - loneil
  - Jsyro
- name: oid4vc-ts-maintainers
  maintainers:
  - TimoGlastra
  members:
  - auer-martin
  - berendsliedrecht
  - marsouin
- name: oid4vc-ts-admin
  maintainers:
  - TimoGlastra
- name: openid-federation-ts-maintainers
  maintainers:
  - TimoGlastra
  members:
  - berendsliedrecht
  - Tommylans
- name: openid-federation-ts-admins
  maintainers:
  - TimoGlastra
- name: eudi-wallet-kit-react-native-maintainers
  maintainers:
  - AlexanderShenshin
  members:
  - akarabashov
- name: fwos-maintainers
  maintainers:
  - jorgefl0
  members:
  - skullquake
- name: identity-credential-admins
  maintainers:
  - davidz25
- name: identity-credential-maintainers
  maintainers:
  - davidz25
  members:
  - 15characterlimi
  - koukarine
  - dyiop
  - GarethCOliver
  - sethmoo
  - sorotokin
  - suzannajiwani
  - kdeus
  - hzawawy
  - TheCoryBarker
- name: lcw-maintainers
  maintainers:
  - alexfigtree
  members:
  - kayaelle
  - dmitrizagidulin
  - jchartrand
  - santhoshvijay11
  - swaroopinamdar
  - rs59
- name: lf-employees
  maintainers:
  - ryjones
  members:
  - SeanBohan
  - strawberry-baked-alaska
- name: mdl-js-maintainers
  maintainers:
  - lukasjhan
  members:
  - hismethod
- name: multiformat-vc-ios-maintainers
  maintainers:
  - gauravping
  members:
  - bhavyachauhan-ping
- name: sd-jwt-dotnet-maintainers
  maintainers:
  - thomas-tran
- name: sd-jwt-kotlin-maintainers
  maintainers:
  - fabian-hk
  - aceshim
- name: sd-jwt-python-maintainers
  maintainers:
  - danielfett
  members:
  - peppelinux
- name: sd-jwt-rust-maintainers
  maintainers:
  - jovfer
  members:
  - Abdulbois
- name: sd-jwt-vc-dm-maintainers
  maintainers:
  - lukasjhan
  members:
  - Dtitkaio
  - Takashiyamam
- name: solid-data-wallet-maintainers
  maintainers:
  - hzbarcea
  members:
  - KyraAssaad
  - edwardsph
  - seilagonzalez
  - NSeydoux
- name: tac
  maintainers:
  - skounis
  members:
  - davidz25
  - rolsonquadras
  - petecool
  - aceshim
  - swcurran
  - wenjing
- name: tsp-maintainers
  maintainers:
  - wenjing
  members:
  - tweedegolf-marc
  - marlonbaeten
  - pohlm01
  - michielp1807
- name: tuvali-maintainers
  maintainers:
  - swatigoel
  members:
  - gsasikumar
  - ckm007
- name: vc-api-developers
  maintainers:
  - jrhender
  members:
  - nichonien
  - ni3gavhane
  - mesaresachin
  - ShikharBhatt
- name: vc-api-maintainers
  maintainers:
  - jrhender
- name: wallet-framework-dotnet-maintainers
  maintainers:
  - CHempel-esatus
  - Dindexx
  - JoTiTu
  - ntsbs
  members:
  - kenkosmowski
repositories:
- name: .github
  teams:
    tac: maintain
  visibility: public
- name: dcql-ts
  teams:
    dcql-ts-maintainers: maintain
    dcql-ts-admin: admin
  visibility: public
- name: governance
  teams:
    tac: maintain
  visibility: public
- name: oid4vc-ts
  teams:
    oid4vc-ts-maintainers: maintain
    oid4vc-ts-admin: admin
  visibility: public
- name: openid-federation-ts
  teams:
    openid-federation-ts-maintainers: maintain
    openid-federation-ts-admins: admin
  visibility: public
- name: eudi-wallet-kit-react-native
  teams:
    eudi-wallet-kit-react-native-maintainers: maintain
  visibility: public
- name: farmworker-wallet-os
  teams:
    fwos-maintainers: maintain
  visibility: public
- name: identity-credential
  teams:
    identity-credential-admins: admin
    identity-credential-maintainers: maintain
  visibility: public
- name: learner-credential-wallet
  teams:
    lcw-maintainers: maintain
  visibility: public
- name: mdl-js
  teams:
    mdl-js-maintainers: maintain
- name: multiformat-vc-ios
  teams:
    multiformat-vc-ios-maintainers: write
  visibility: public
- name: PyDentity-Wallet
  teams:
    pydentity-wallet-maintainers: write
  visibility: public
- name: sd-jwt-dotnet
  teams:
    sd-jwt-dotnet-maintainers: maintain
  visibility: public
- name: sd-jwt-kotlin
  teams:
    sd-jwt-kotlin-maintainers: maintain
  visibility: public
- name: sd-jwt-python
  teams:
    sd-jwt-python-maintainers: maintain
  visibility: public
- name: sd-jwt-rust
  teams:
    sd-jwt-rust-maintainers: maintain
  visibility: public
- name: sd-jwt-vc-dm
  teams:
    sd-jwt-vc-dm-maintainers: maintain
  visibility: public
- name: solid-data-wallet
  teams:
    solid-data-wallet-maintainers: maintain
  visibility: public
- name: tsp
  teams:
    tsp-maintainers: maintain
  visibility: public
- name: tuvali
  teams:
    tuvali-maintainers: maintain
  visibility: public
- name: tuvali-ios-swift
  teams:
    tuvali-maintainers: maintain
  visibility: public
- name: vc-api
  teams:
    vc-api-maintainers: maintain
    vc-api-developers: write
  visibility: public
- name: wallet-framework-dotnet
  teams:
    wallet-framework-dotnet-maintainers: maintain
  visibility: public
