teams:
- name: credhub-maintainers
  maintainers:
  - cre8
  members:
  - mustafasalfiti
- name: credhub-admin
  maintainers:
  - cre8
- name: eudi-wallet-kit-react-native-maintainers
  maintainers:
  - AlexanderShenshin
  members:
  - akarabashov
- name: fwos-maintainers
  maintainers:
  - jorgefl0
  members:
  - skullquake
- name: identity-credential-admins
  maintainers:
  - davidz25
- name: identity-credential-maintainers
  maintainers:
  - davidz25
  members:
  - 15characterlimi
  - dritan-x
  - dyiop
  - GarethCOliver
  - sethmoo
  - sorotokin
  - suzannajiwani
  - kdeus
  - hzawawy
  - TheCoryBarker
- name: lcw-maintainers
  maintainers:
  - tkuhrt
  members:
  - alexfigtree
  - kayaelle
  - dmitrizagidulin
  - jchartrand
- name: lf-employees
  maintainers:
  - ryjones
  members:
  - SeanBohan
  - strawberry-baked-alaska
- name: mdl-js-maintainers
  maintainers:
  - lukasjhan
  members:
  - hismethod
- name: multiformat-vc-ios-maintainers
  maintainers:
  - gauravping
  members:
  - bhavyachauhan-ping
- name: sd-jwt-dotnet-maintainers
  maintainers:
  - thomas-tran
- name: sd-jwt-kotlin-maintainers
  maintainers:
  - fabian-hk
  - aceshim
- name: sd-jwt-python-maintainers
  maintainers:
  - danielfett
  members:
  - peppelinux
- name: sd-jwt-rust-maintainers
  maintainers:
  - jovfer
  members:
  - Abdulbois
- name: tsp-maintainers
  maintainers:
  - wenjing
  members:
  - tweedegolf-marc
  - marlonbaeten
- name: tuvali-maintainers
  maintainers:
  - tkuhrt
  members:
  - gsasikumar
  - ckm007
  - swatigoel
- name: vc-api-developers
  maintainers:
  - jrhender
  members:
  - nichonien
- name: vc-api-maintainers
  maintainers:
  - jrhender
- name: wallet-framework-dotnet-maintainers
  maintainers:
  - CHempel-esatus
  - Dindexx
  - JoTiTu
  - ntsbs
  members:
  - kenkosmowski
repositories:
- name: .github
  visibility: public
- name: credhub
  teams:
    credhub-maintainers: maintain
    credhub-admin: admin
  visibility: public
- name: eudi-wallet-kit-react-native
  teams:
    eudi-wallet-kit-react-native-maintainers: maintain
  visibility: public
- name: farmworker-wallet-os
  teams:
    fwos-maintainers: maintain
  visibility: public
- name: identity-credential
  teams:
    identity-credential-admins: admin
    identity-credential-maintainers: maintain
  visibility: public
- name: learner-credential-wallet
  teams:
    lcw-maintainers: maintain
  visibility: public
- name: mdl-js
  teams:
    mdl-js-maintainers: maintain
- name: multiformat-vc-ios
  teams:
    multiformat-vc-ios-maintainers: write
  visibility: public
- name: sd-jwt-dotnet
  teams:
    sd-jwt-dotnet-maintainers: maintain
  visibility: public
- name: sd-jwt-kotlin
  teams:
    sd-jwt-kotlin-maintainers: maintain
  visibility: public
- name: sd-jwt-python
  teams:
    sd-jwt-python-maintainers: maintain
  visibility: public
- name: sd-jwt-rust
  teams:
    sd-jwt-rust-maintainers: maintain
  visibility: public
- name: tsp
  teams:
    tsp-maintainers: maintain
  visibility: public
- name: tuvali
  teams:
    tuvali-maintainers: maintain
  visibility: public
- name: tuvali-ios-swift
  teams:
    tuvali-maintainers: maintain
  visibility: public
- name: vc-api
  teams:
    vc-api-maintainers: maintain
    vc-api-developers: write
  visibility: public
- name: wallet-framework-dotnet
  teams:
    wallet-framework-dotnet-maintainers: maintain
  visibility: public
